In [ ]:
# Libraries in Python : 2L+
# What is Numpy
  # Numerical Python







In [ ]:
#Libraries Install
!pip install numpy




In [ ]:
#Libraries import

import numpy as np



In [ ]:
#1-D Array
a = np.array([1,2, 3,4,5])
print(a)


[1 2 3 4 5]


In [ ]:
#2-D Arrays
b = np.array([[1,2 ,3,4,5], [6,7,8,9,10]])
print(b)

b[1][2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8

In [ ]:
#Creating an array with zeros element
c = np.zeros(20)
# print(type(c))
print(c)

c.dtype

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


dtype('float64')

In [ ]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
d = np.ones(30)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.empty(10)

array([4.64099441e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.61213888e-310, 2.67819039e+184, 4.90482938e-062, 5.02822527e-091,
       1.34999806e+161, 7.01413755e-009])

In [ ]:
#range function of python
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
#arange function with steps
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#Specify our datatype

x = np.ones(5 ,dtype = np.int32)
x



array([1, 1, 1, 1, 1], dtype=int32)

In [ ]:
y =  np.zeros(10  , dtype = np.int64)
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Sorting


arr = np.array([2,1,5,9,8,7,89,91,25,200])
print(arr)


c = np.sort(arr)
c[::-1]






[  2   1   5   9   8   7  89  91  25 200]


array([200,  91,  89,  25,   9,   8,   7,   5,   2,   1])

In [ ]:
l = [54,87,98,95,65]
l.sort(reverse = True)
print(l)

[98, 95, 87, 65, 54]


In [ ]:
#Concatenate
a = np.array([1,2,3,4,5])
b = np.array([7,8,9,6,5,10])


np.concatenate((a , b))



array([ 1,  2,  3,  4,  5,  7,  8,  9,  6,  5, 10])

In [ ]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_exam = np.array(
    [
      [[0,1,2,3],
      [4,5,6,7]],

      [[0,1,2,3],
      [4,5,6,7]],

      [[0,1,2,3],
      [4,5,6,7]]
     ]
)

array_exam

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
array_exam.ndim

3

In [ ]:
array_exam.size

24

In [ ]:
array_exam.shape

(3, 2, 4)

In [ ]:
#Reshape of the array

ar = np.arange(6)
print(ar)

[0 1 2 3 4 5]


In [ ]:
reshape = ar.reshape(3,2)
print(reshape)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
ar.reshape(1 ,-1) #Columns reshaping


array([[0, 1, 2, 3, 4, 5]])

In [ ]:
ar.reshape(-1,1)#Rows reshape

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
ar

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Numpy Assignments

1. Create a 1-D array of 10 integers.
2. Create a 2-D array of 5 rows and 3 columns.
3. Create a 3-D array of 2 layers, each containing 3 rows and 4 columns.
4. Create an array of 10 zeros.
5. Create an array of 10 ones.
6. Create an array of 10 random numbers.
7. Create an array of 10 evenly spaced numbers between 1 and 10.
8. Create an array of 10 numbers that are multiples of 3.
9. Sort an array of 10 random numbers in ascending order.
10. Sort an array of 10 random numbers in descending order.
11. Find the maximum value in an array of 10 random numbers.
12. Find the minimum value in an array of 10 random numbers.
13. Find the mean of an array of 10 random numbers.
14. Find the median of an array of 10 random numbers.
15. Concatenate two arrays of 5 random numbers each.
16. Split an array of 10 random numbers into two arrays of 5 elements each.
17. Reshape an array of 12 elements into a 3x4 matrix.
18. Transpose a 3x4 matrix.
19. Calculate the addition of  3x3 matrices.
20. Calculate the Subtraction and multiplication 3x3 matrix.

In [ ]:
#1. Create a 1-D array of 10 integers.

import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#2. Create a 2-D array of 5 rows and 3 columns.

a = np.array([[1,2,3],

              [4,5,6],

              [7,8,9],

              [10,11,12],

              [13,14,15],
              ])

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
#3. Create a 3-D array of 2 layers, each containing 3 rows and 4 columns.

a = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[13,14,15,16],
               [17,18,19,20],
               [21,22,23,24]]])

print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
#4. Create an array of 10 zeros.
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#5. Create an array of 10 ones.

a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#6. Create an array of 10 random numbers.

a = np.empty(10)
print(a)


[1.48e-323 2.96e-323 4.45e-323 5.93e-323 7.41e-323 8.89e-323 1.04e-322
 1.19e-322 1.33e-322 1.48e-322]


In [ ]:
#7. Create an array of 10 evenly spaced numbers between 1 and 10.

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#8. Create an array of 10 numbers that are multiples of 3.

a = np.arange(3,31,3)
print(a)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#9. Sort an array of 10 random numbers in ascending order.
a = np.random.rand(10)
b = np.sort(a)
print(b)

[0.18738404 0.27252982 0.28076961 0.38497278 0.38586462 0.43031105
 0.47252041 0.6527953  0.80967168 0.92921868]


In [ ]:
#10. Sort an array of 10 random numbers in descending order.
a = np.random.rand(10)
b = np.sort(a)[::-1]
print(b)

[0.96510032 0.96091703 0.84163326 0.81838581 0.81352155 0.66633141
 0.58266228 0.54088141 0.50318992 0.43025325]


In [ ]:
#11. Find the maximum value in an array of 10 random numbers.

a = np.random.rand(10)
b = np.max(a)
print(b)

0.9412849846917949


In [ ]:
#12. Find the minimum value in an array of 10 random numbers.
a = np.random.rand(10)
b = np.min(a)
print(b)

0.09875713828956512


In [ ]:
#13. Find the mean of an array of 10 random numbers.
a = np.random.rand(10)
b = np.mean(a)
print(b)

0.5167358940498932


In [ ]:
#14. Find the median of an array of 10 random numbers.
a = np.random.rand(10)
b = np.median(a)
print(b)

0.542009450660742


In [ ]:
#15. Concatenate two arrays of 5 random numbers each.
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#16. Split an array of 10 random numbers into two arrays of 5 elements each.
a = np.random.rand(10)
b = np.split(a,2)
print(b)

[array([0.44759332, 0.70814148, 0.97848633, 0.64805242, 0.11669911]), array([0.77876522, 0.10818685, 0.82016525, 0.85470141, 0.58407   ])]


In [ ]:
#17. Reshape an array of 12 elements into a 3x4 matrix.
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b = a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#18. Transpose a 3x4 matrix.
a = np.array([[ 1, 2, 3, 4],
              [ 5, 6, 7, 8],
              [ 9, 10, 11, 12]])
b = np.transpose(a)
print(b)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
#19. Calculate the addition of  3x3 matrices.
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

c = np.add(a,b)
print(c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
c = a+b
print(c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
#20. Calculate the Subtraction and multiplication 3x3 matrix.
#substract
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

c = np.subtract(a,b)
print(c)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
#substract
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
c = a-b
print(c)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
#multiply
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
c = np.multiply(a,b)
print(c)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
#multiply
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])
c = a*b
print(c)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
